allowBuilds:
  '@firebase/util': true
  cypress: true
  es5-ext: true
  protobufjs: true
  re2: true
onlyBuiltDependencies:
  - '@firebase/util'
  - core-js
  - cypress
  - es5-ext
  - protobufjs
  - re2
